import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs"
import deved from "../public/dev-ed-wave.png"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
       <section className='min-h-scre'>
        {/* nav bar */}
          <nav className=' py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className=' text-xl '> devloped by me</h1>
            <ul className='flex items-center'>
              <li>
              <BsFillMoonStarsFill
                  // onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8' href="">Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10 py-10'>
            <h2 className=' text-5xl py2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl'>Redouane Hitachi</h2>
            <h3 className=' text-2xl py-2 dark:text-white md:text-3xl '>Developer</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl'>Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!</p>
          </div>
          <div className='flex justify-center gap-16 text-gray-600 text-5xl dark:text-gray-400 '>
             <AiFillYoutube />
             <AiFillLinkedin/>
             <AiFillTwitterCircle/>
            
          </div>
          <div className=' mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96' >
            <Image src={deved}  layout='fill' alt="" />
          </div>
        </section>
      </main>
      
    </div>
  )
}
